---

- name: Munge Group
  ansible.builtin.group:
    name: munge
    gid: 201
    state: present

- name: Slurm Group
  ansible.builtin.group:
    name: slurm
    gid: 202
    state: present

- name: Munge User
  ansible.builtin.user:
    name: munge
    comment: ""
    uid: 201
    group: munge
    shell: /sbin/nologin
    createhome: no
    system: yes

- name: Slurm User
  ansible.builtin.user:
    name: slurm
    comment: ""
    uid: 202
    group: slurm
    shell: /sbin/nologin
    createhome: no
    system: yes

- name: Create Munge Key
  ansible.builtin.command: create-munge-key
  args:
    creates: "{{ cluster_vars.munge_dir }}/munge.key"

- name: Munge Directory
  ansible.builtin.file:
    path: "{{ cluster_vars.munge_dir }}"
    owner: munge
    group: munge
    state: directory
    mode: 0700

- name: Secure Munge PRNG
  ansible.builtin.file:
    path: /var/lib/munge
    owner: munge
    group: munge
    state: directory
    mode: 0700

- name: Fetch Munge Key
  run_once: true
  ansible.builtin.fetch:
    flat: true
    src: "{{ cluster_vars.munge_dir }}/munge.key"
    dest: "{{ role_path }}/files/"

- name: Copy Munge Key to Cluster
  ansible.builtin.copy:
    src: munge.key
    dest: "{{ cluster_vars.munge_dir }}/munge.key"
    owner: munge
    group: munge
    mode: 0400

- name: Slurm Directory
  ansible.builtin.file:
    path: "{{ cluster_vars.slurm_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Slurm Configuration File
  ansible.builtin.template:
    src: slurm.conf
    dest: "{{ cluster_vars.slurm_dir }}/slurm.conf"
    owner: root
    group: root
    mode: 0644

- name: Slurm Log Directory
  ansible.builtin.file:
    path: "{{ cluster_vars.log_dir }}/slurm"
    owner: slurm
    group: slurm
    state: directory
    mode: 0755

- name: Munge Log Directory
  ansible.builtin.file:
    path: "{{ cluster_vars.log_dir }}/munge"
    owner: munge
    group: munge
    state: directory
    mode: 0755

- name: Slurm Common RPM List
  ansible.builtin.set_fact:
    pkg_list:
      - slurm
      - slurm-perlapi
      - slurm-devel

- name: Slurm Common RPM Install
  ansible.builtin.dnf:
    name: "{{ pkg_list }}"
    state: installed

- name: Start Munge Service
  ansible.builtin.service:
    name: munge
    state: started
    enabled: yes
