---

- name: Slurm Compute RPM List
  ansible.builtin.set_fact:
    pkg_list:
      - slurm-slurmd
      - slurm-pam_slurm
      - slurm-contribs

- name: Slurm Compute RPM Install
  ansible.builtin.dnf:
    name: "{{ pkg_list }}"
    state: installed

- name: Configure Slurmd
  ansible.builtin.shell:
    cmd: echo "SLURMD_OPTIONS=--conf-server {{ hostvars['server']['ansible_facts']['nodename'] }}" > /etc/sysconfig/slurmd
  args:
    creates: "/etc/sysconfig/slurmd"

- name: Slurm Service
  ansible.builtin.service:
    name: slurmd
    state: started
    enabled: yes
