---
- name: Copy Cluster Hosts File
  copy:
    src: /etc/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags: common_init

- set_fact: abort=true

- name: Upgrade All Packages
  dnf:
    name: "*"
    state: latest
  tags: common_init

- name: Check the EPEL9 RPM Key
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
  tags: common_init

- name: Common RPM Initialization List
  set_fact:
    pkg_list:
      - vim
      - python3-pip
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  when:
    - abort is undefined
  tags: common_init

- name: Install Common RPMs
  dnf:
    name: "{{ pkg_list }}"
    state: installed
    allowerasing: true
  when:
    - abort is undefined
  tags: common_init
