---

- name: Copy Cluster Hosts File
  copy:
    src: /etc/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags: common_init

- name: Copy RSA key
  copy:
    src: "{{ cluster_vars.root_home }}/.ssh/id_rsa"
    dest: "{{ cluster_vars.user_home }}/.ssh/id_rsa"
    owner: "{{ cluster_vars.username }}"
    group: "{{ cluster_vars.username }}"
    mode: 0700
  tags: common_init

- set_fact: abort=true

- name: Upgrade All Packages
  dnf:
    name: "*"
    state: latest
  tags: common_init

- name: Check the EPEL9 RPM Key
  rpm_key:
    state: present
    key: "{{ cluster_vars.epel9_gpg_key_url }}"
  tags: common_init

- name: Common RPM Initialization List
  set_fact:
    pkg_list:
      - vim
      - munge
      - "{{ cluster_vars.epel9_rpm_url }}"
  when:
    - abort is undefined
  tags: common_init

- name: Install Common RPMs
  dnf:
    name: "{{ pkg_list }}"
    state: installed
    allowerasing: true
  when:
    - abort is undefined
  tags: common_init
