---

- name: Slurm Database Configuration File
  ansible.builtin.copy:
    src: slurmdbd.conf
    dest: "{{ cluster_vars.slurm_dir }}/slurmdbd.conf"
    owner: root
    group: root
    mode: 0600

- name: Slurm Database RPM List
  ansible.builtin.set_fact:
    pkg_list:
      - slurm-slurmdbd
      - mariadb-server
      - python3-PyMySQL

- name: Slurm Database RPM Install
  ansible.builtin.dnf:
    name: "{{ pkg_list }}"
    state: installed

- name: MariaDB Service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Slurm Account DB
  community.mysql.mysql_db:
    name: slurm_acct_db
    state: present
    login_unix_socket: "{{ cluster_vars.mysql_socket }}"

- name: Slurm MySQL User
  community.mysql.mysql_user:
    name: slurm
    host: server
    login_unix_socket: "{{ cluster_vars.mysql_socket }}"
    password: '*97C165CCACCAD8DFE21431AA259E3AF9A593C933'
    encrypted: yes
    priv: 'slurm_acct_db.*:ALL,GRANT'
    state: present
    update_password: always

- name: Slurm MySQL User
  community.mysql.mysql_user:
    name: slurm
    host: "{{ cluster_vars.cluster_name }}"
    login_unix_socket: "{{ cluster_vars.mysql_socket }}"
    password: '*97C165CCACCAD8DFE21431AA259E3AF9A593C933'
    encrypted: yes
    priv: 'slurm_acct_db.*:ALL,GRANT'
    state: present
    update_password: always

- name: Slurm Database Service
  ansible.builtin.service:
    name: slurmdbd
    state: started
    enabled: yes
