---

- name: Slurm Server RPM List
  set_fact:
    pkg_list:
      - slurm-slurmctld

- name: Slurm Server RPM Install
  dnf:
    name: "{{ pkg_list }}"
    state: installed

- name: Slurm Controller Service
  service:
    name: slurmctld
    state: started
    enabled: yes

- name: Create Cluster
  command:
    cmd: sacctmgr -i create cluster vslurm
  register: sacctmgr_cmd
  failed_when: sacctmgr_cmd.rc >= 2
  changed_when: sacctmgr_cmd.rc == 0
