---

- name: Slurm Login RPM List
  ansible.builtin.set_fact:
    pkg_list:
      - slurm-contribs

- name: Slurm Login RPM Install
  ansible.builtin.dnf:
    name: "{{ pkg_list }}"
    state: installed
