---

- name: NFS Shared Mount Directory
  ansible.builtin.file:
    path: /shared
    owner: root
    group: root
    state: directory
    mode: 0755

- name: NFS Home Directory
  ansible.builtin.file:
    path: /mnt/nfs/home
    owner: root
    group: root
    state: directory
    mode: 0755

- name: NFS Client RPM List
  ansible.builtin.set_fact:
    pkg_list:
      - nfs-utils

- name: NFS Client RPM Install
  ansible.builtin.dnf:
    name: "{{ pkg_list }}"
    state: installed

- name: NFS Shared Client Mount
  ansible.posix.mount:
    name: /shared
    src: "{{ hostvars['nfs-server']['ansible_ssh_host'] }}:/shared"
    fstype: nfs
    opts: defaults
    state: mounted

- name: NFS Home Client Mount
  ansible.posix.mount:
    name: /mnt/nfs/home
    src: "{{ hostvars['nfs-server']['ansible_ssh_host'] }}:/home"
    fstype: nfs
    opts: defaults
    state: mounted

- name: Enable NFS Home Directories
  ansible.builtin.command: setsebool -P use_nfs_home_dirs on
