#cloud-config

package_update: true
package_upgrade: true
packages:
  - vim
  - git
  - python3-pip

write_files:
  - path: ${root_home}/ansible_hosts
    content: |
      ${indent(6, ansible_hosts)}
  - path: ${root_home}/ansible_variables.yaml
    content: |
      ${indent(6, ansible_variables)}
  - path: ${root_home}/.ssh/id_rsa
    permissions: '0o600'
    defer: true
    encoding: base64
    content: |
      ${indent(6, private_key_base64)}
