#!/bin/bash -x

# write hosts file
%{ for node in nodes ~}
echo ${node.private_ip} ${node.private_dns} ${node.tags_all.host_alias} >> /etc/hosts
%{ endfor ~}

export ANSIBLE_INVENTORY=${ansible_inventory}
echo "export ANSIBLE_INVENTORY=${ansible_inventory}" >> /root/.bashrc
export ANSIBLE_REMOTE_USER=${ansible_remote_user}
echo "export ANSIBLE_REMOTE_USER=${ansible_remote_user}" >> /root/.bashrc
export ANSIBLE_BECOME=True
echo "export ANSIBLE_BECOME=True" >> /root/.bashrc
export ANSIBLE_HOST_KEY_CHECKING=False
echo "export ANSIBLE_HOST_KEY_CHECKING=False" >> /root/.bashrc

/usr/bin/pip install --no-input ansible && \
    /usr/bin/git clone ${git_args} ${git_repo} ${git_dir}
cd ${ansible_dir} && \
    ansible-playbook -v ${ansible_playbook} --tags common_init && \
    ansible-playbook -v ${ansible_playbook} --tags slurm_common && \
    ansible-playbook -v ${ansible_playbook} --tags slurm_database && \
    ansible-playbook -v ${ansible_playbook} --tags slurm_server && \
    ansible-playbook -v ${ansible_playbook} --tags slurm_login && \
    ansible-playbook -v ${ansible_playbook} --tags slurm_compute && \
    ansible all -m ansible.builtin.reboot && \
    ansible-playbook -v ${ansible_playbook}

# Shutdown the instance after a few minutes
shutdown +30
