#!/bin/bash -x

/usr/bin/cat /root/cluster_hosts >> /etc/hosts

export ANSIBLE_INVENTORY=${ansible_inventory}
echo ANSIBLE_INVENTORY=${ansible_inventory} >> /etc/profile.d/bashrc
export ANSIBLE_REMOTE_USER=${ansible_remote_user}
echo ANSIBLE_REMOTE_USER=${ansible_remote_user} >> /etc/profile.d/bashrc
export ANSIBLE_BECOME=True
echo ANSIBLE_BECOME=True >> /etc/profile.d/bashrc
export ANSIBLE_HOST_KEY_CHECKING=False
echo ANSIBLE_HOST_KEY_CHECKING=False >> /etc/profile.d/bashrc

/usr/bin/pip install --no-input ansible && \
    /usr/bin/git clone ${git_args} ${git_repo} ${git_dir}
cd ${ansible_dir} && \
    ansible-playbook -v ${ansible_playbook} --tags common_init && \
    ansible-playbook -v ${ansible_playbook} --tags slurm_common && \
    ansible-playbook -v ${ansible_playbook} --tags slurm_database && \
    ansible-playbook -v ${ansible_playbook} --tags slurm_server && \
    ansible-playbook -v ${ansible_playbook} --tags slurm_login && \
    ansible-playbook -v ${ansible_playbook} --tags slurm_compute && \
    ansible all -m ansible.builtin.reboot && \
    ansible-playbook -v ${ansible_playbook}

# Shutdown the instance after a few minutes
shutdown +30
