#!/bin/bash

# Make the prompt useful
/usr/bin/echo "export NICKNAME=${nickname}" > /etc/profile.d/prompt.sh
/usr/bin/echo "export PS1=\"[\$NICKNAME][\u@\h:\l \W]\\$ \"" >> /etc/bashrc

# Shutdown the instance after a few hours
shutdown +300
