#!/bin/bash -x

/usr/bin/cat /root/cluster_hosts >> /etc/hosts

/usr/bin/pip install --no-input ansible && \
    /usr/bin/git clone ${git_args} ${git_repo} ${git_dir} && \
    #/usr/bin/cd ${ansible_dir} && \
    #/usr/local/bin/ansible-playbook -v ${ansible_playbook}

# Shutdown the instance after a few minutes
shutdown +300
