#cloud-config

package_update: true
package_upgrade: true
packages:
  - git
  - python3-pip

write_files:
  - path: /root/cluster_hosts
    content: |
      ${indent(6, cluster_hosts)}
  - path: /root/ansible_hosts
    content: |
      ${indent(6, ansible_hosts)}
  - path: /root/.ssh/id_rsa
    permissions: '0o600'
    defer: true
    encoding: base64
    content: |
      ${indent(6, private_key_base64)}

# ansible:
#   install_method: pip
#   package_name: ansible
#   run_user: root
#   setup_controller:
#     repositories:
#       path: /root/
#       source: "git@github.com:UCL-ARC/terraform-aws-vslurm.git -b 8-configure-the-deployer-instance"
#     run_ansible:
#       - playbook_dir: /root/terraform-aws-vslurm/ansible
#         playbook_name: test.yaml
#         timeout: 300
#         forks: 1
#         private_key: /root/.ssh/id_rsa
#         inventory: /root/ansible_hosts
