#cloud-config

package_update: true
package_upgrade: true
# yum_repos:
#   epel-release:
#     baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
#     enabled: true
#     name: Extra Packages for Enterprise Linux 9 - Release
packages:
  - ansible
  - git
  - python3-pip
#  - pdsh
#  - pdsh-rcmd-ssh

runcmd:
  - [ sh, -c, "echo '${cluster_hosts}' >> /etc/hosts "]

# users:
# - name: ansible
#   gecos: Ansible User
#   shell: /bin/bash
#   groups: users,admin,wheel
#   sudo: ALL=(ALL) NOPASSWD:ALL

# ansible:
#   install_method: pip
#   package_name: ansible
#   run_user: ansible
#   setup_controller:
#     repositories:
#       - path: /home/ansible/terraform-aws-vslurm
#         source: git@github.com:UCL-ARC/terraform-aws-vslurm.git
#     run_ansible:
#       - playbook_dir: /home/ansible/terraform-aws-vslurm/ansible
#         playbook_name: cluster.yaml
#         timeout: 120
#         forks: 1
#         private_key: /home/ansible/.ssh/id_rsa
#         inventory: /home/ansible/ansible_hosts

# write_files:
#   - path: "/home/ansible/.ssh/id_rsa"
#     owner: ansible:ansible
#     permissions: '0o600'
#     defer: true
#     encoding: base64
#     content: |
#       ${private_key_base64}
