#!/bin/bash -x

pip install --no-input ansible && \
    git clone ${git_args} ${git_repo} && \
    cd ./terraform-aws-vslurm/ansible && \
    ansible-playbook -v test.yaml

# Shutdown the instance after a few hours
shutdown +300
