#!/bin/bash

# Make the prompt useful
/usr/bin/echo "export NICKNAME=${nickname}" > /etc/profile.d/prompt.sh
/bin/sed -i -e 's/\\h/$NICKNAME/g' /etc/bashrc

# Update packages
dnf update -y --allowerasing
ARCH=$( /bin/arch )
subscription-manager repos --enable codeready-builder-for-rhel-9-$(ARCH)-rpms
dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

# Shutdown the instance after a few hours
shutdown +300
